<a href="https://colab.research.google.com/github/JimmyXiaodong/pytorch-study/blob/master/model_lstm_pad_packed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
from torch.nn.utils.rnn import pack_sequence


a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5])
c = torch.tensor([6])

pack_sequence([a, b, c])

PackedSequence(data=tensor([1, 4, 6, 2, 5, 3]), batch_sizes=tensor([3, 2, 1]), sorted_indices=None, unsorted_indices=None)

In [ ]:
import torch as t
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence

# a = t.tensor([[1,2,3], [6,0,0], [4,5,0]])
a = t.tensor([[7,8,0],[9,0,0],[10,0,0]])
lengths = t.tensor([2,1,1])

In [ ]:
a_lengths, idx = lengths.sort(0, descending=True)

In [ ]:
a_lengths

tensor([2, 1, 1])

In [ ]:
idx

tensor([0, 1, 2])

In [ ]:
temp, un_idx = t.sort(idx, dim=0)

In [ ]:
un_idx

tensor([0, 1, 2])

In [ ]:
temp

tensor([0, 1, 2])

In [ ]:
a = a[idx]

In [ ]:
a

tensor([[ 7,  8,  0],
        [ 9,  0,  0],
        [10,  0,  0]])

In [ ]:
idx

tensor([0, 1, 2])

In [ ]:
emb = t.nn.Embedding(20, 2, padding_idx=0)
lstm = t.nn.LSTM(input_size=2, hidden_size=4, batch_first=True)

a_input = emb(a)

a_input

tensor([[[-1.1957,  0.9629],
         [-0.0566,  0.3349],
         [ 0.0000,  0.0000]],

        [[ 1.5342,  1.1001],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000]],

        [[ 0.8921,  0.0523],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000]]], grad_fn=<EmbeddingBackward>)

In [ ]:
a_lengths

tensor([2, 1, 1])

In [ ]:
a_packed_input = t.nn.utils.rnn.pack_padded_sequence(input=a_input, lengths=a_lengths, batch_first=True)

a_packed_input

PackedSequence(data=tensor([[-1.1957,  0.9629],
        [ 1.5342,  1.1001],
        [ 0.8921,  0.0523],
        [-0.0566,  0.3349]], grad_fn=<PackPaddedSequenceBackward>), batch_sizes=tensor([3, 1]), sorted_indices=None, unsorted_indices=None)

In [ ]:
packed_out, _ = lstm(a_packed_input)

packed_out

PackedSequence(data=tensor([[ 0.0250,  0.1487, -0.0471,  0.1455],
        [ 0.0609,  0.0426,  0.2460,  0.3343],
        [ 0.0500,  0.0363,  0.1835,  0.2368],
        [ 0.0540,  0.2297,  0.0298,  0.2458]], grad_fn=<CatBackward>), batch_sizes=tensor([3, 1]), sorted_indices=None, unsorted_indices=None)

In [ ]:
out, _ = pad_packed_sequence(packed_out, total_length=3, batch_first=True)

In [ ]:
out

tensor([[[ 0.0250,  0.1487, -0.0471,  0.1455],
         [ 0.0540,  0.2297,  0.0298,  0.2458],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 0.0609,  0.0426,  0.2460,  0.3343],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 0.0500,  0.0363,  0.1835,  0.2368],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]]], grad_fn=<TransposeBackward0>)

In [ ]:
out = t.index_select(out, 0, un_idx)

In [ ]:
out

tensor([[[-0.1458, -0.0717,  0.0040,  0.1584],
         [-0.1350, -0.0723,  0.0484,  0.1315],
         [-0.0200, -0.0661,  0.1174,  0.0087]],

        [[-0.2075, -0.1383,  0.1451,  0.2237],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[-0.1805, -0.1080,  0.0656,  0.1926],
         [-0.1433, -0.1341,  0.0206,  0.2294],
         [ 0.0000,  0.0000,  0.0000,  0.0000]]], grad_fn=<IndexSelectBackward>)

In [ ]:
b = 